name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu_latest

steps:
  -uses: actions/checkout@v2
  -name: Use node.js
  -uses: actions/setup-node@v1
    with: node-version: '14.x'
  -run: npm install 
  -run: npm test/node
  env: 
    CI: true  

